server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /healthz {
        default_type text/plain;
        return 200 'ok';
    }

    location ~* \.js$ {
        default_type application/javascript;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Cache-Control "public, max-age=300" always;
    }

    location / {
        autoindex off;
        try_files $uri =404;
    }
}
